services:
  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/app
    working_dir: /app
    command: ["python", "main.py"]
    ports:
      - "80:8000"
    restart: always
