services:
  db:
    image: postgres:15
    container_name: psql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2002
      POSTGRES_DB: crypto
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - ../:/app
    working_dir: /app
    command: ["python", "main.py"]
    restart: always

volumes:
  pgdata:
